apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-ui
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
      - image: brenobusnello/breno:4a95ec5a079917ac8a069efc4aba8ae9f073d14c
        name: demo-ui
        ports:
        - containerPort: 80
