apiVersion: apps/v1
kind: Deployment
metadata:
name: demo-ui
spec:
replicas: 1
revisionHistoryLimit: 3
selector:
matchLabels:
app: demo-ui
template:
metadata:
labels:
app: demo-ui
spec:
containers:
- image: brenobusnello/breno:e6a7f09c7b016787203eeb8fb90b67f90d307236
name: demo-ui
ports:
- containerPort: 80
